### ISSUE TITLE
Error:timeout of 120000ms exceeded

### ISSUE THREAD

**Issue by mxm646690173** [THUDM/CodeGeeX#11]
莫名原因出现该报错,就普通正常操作后,空闲一段时间,就会报这个

Error:timeout of 120000ms exceeded

来源:CodeGeeX(扩展)

**Comment by Stanislas0** [comment]
您好！我们刚刚更新了新版（v1.0.3）的插件，您可以更新试一下是否还有相同的问题？

**Comment by mxm646690173** [comment]
> 您好！我们刚刚更新了新版（v1.0.3）的插件，您可以更新试一下是否还有相同的问题？

好的,我现在已经使用1.0.3版本插件, 今天的报错信息如下:

Error: getaddrinfo ENOTFOUND tianqi.aminer.cn

来源:CodeGeeX(扩展)

**Comment by Stanislas0** [comment]
> Error:timeout of 120000ms exceeded

您好！这个报错主要是因为生成时长超过了120s，当前我们用户数量逐渐增加，有些时段服务器压力较大，会出现个别超时情况。后续我们会对这方面进行优化，还请您谅解！如果出现长时间、频繁的超时现象，您可以再跟我们反馈，我们看具体出了什么问题，感谢！

**Comment by mxm646690173** [comment]
> > Error:timeout of 120000ms exceeded
> 
> 您好！这个报错主要是因为生成时长超过了120s，当前我们用户数量逐渐增加，有些时段服务器压力较大，会出现个别超时情况。后续我们会对这方面进行优化，还请您谅解！如果出现长时间、频繁的超时现象，您可以再跟我们反馈，我们看具体出了什么问题，感谢！

好的,非常感谢解答

**Comment by Stanislas0** [comment]
> > > Error:timeout of 120000ms exceeded
> > 
> > 
> > 您好！这个报错主要是因为生成时长超过了120s，当前我们用户数量逐渐增加，有些时段服务器压力较大，会出现个别超时情况。后续我们会对这方面进行优化，还请您谅解！如果出现长时间、频繁的超时现象，您可以再跟我们反馈，我们看具体出了什么问题，感谢！
> 
> 好的,非常感谢解答

您好！我们最近对CodeGeeX进行了大幅优化加速，您可以体验一下新版插件，是否还有延迟
