### ISSUE TITLE
工程项目里面的deployment下的server_gradio.py如何在多GPU下运行起来

### ISSUE THREAD

**Issue by Carson-yy** [THUDM/CodeGeeX#120]

**Comment by Stanislas0** [comment]
你好，多GPU情况下，使用torch distributed启动程序，在rank0上运行gradio的部分即可

**Comment by Carson-yy** [comment]
> 你好，多GPU情况下，使用torch distributed启动程序，在rank0上运行gradio的部分即可
多谢
