### ISSUE TITLE
Are there any plans to launch the jetbrain plugin？

### ISSUE THREAD

**Issue by zhangyucumt** [THUDM/CodeGeeX#14]
Are there any plans to launch the jetbrain plugin？

**Comment by Stanislas0** [comment]
Sure! We're currently working on the JetBrains plugin, which will be ready soon. 

> Are there any plans to launch the jetbrain plugin？

**Comment by jinzhongjia** [comment]
> Sure! We're currently working on the JetBrains plugin, which will be ready soon.
> 
> > Are there any plans to launch the jetbrain plugin？

Are there any plans to launch the jetbrain plugin？

**Comment by Stanislas0** [comment]
> Are there any plans to launch the jetbrain plugin？

@zhangyucumt Hi！CodeGeeX for Jetbrains is now available, [click to download](https://plugins.jetbrains.com/plugin/20587-codegeex) or search "codegeex" in the plugin market. Welcome to have a try!

**Comment by Stanislas0** [comment]
> > Sure! We're currently working on the JetBrains plugin, which will be ready soon.
> > > Are there any plans to launch the jetbrain plugin？
> 
> Are there any plans to launch the vim(neovim) plugin？

Hi! CodeGeeX for vim is on the plan, if you are interested in joining us for the development, we highly appreciate it!

**Comment by Stanislas0** [comment]
> Are there any plans to launch the jetbrain plugin？

Hi! CodeGeeX for Jetbrains is now available in the plugin marketplace, please check https://plugins.jetbrains.com/plugin/20587-codegeex

**Comment by yhyu13** [comment]
@Stanislas0 Hi, I traveled back from time and that Jetbrain rider 2022.3.2 has succeeded in installing the plugin, but failed to retrieve any completion. 

![rider64_zY0Xadr0BU](https://user-images.githubusercontent.com/19365678/220179845-e513d4e8-d536-4db0-962b-a188d6142c46.png)


So, is there any active support landing on upgrading to later version of jetbrain at this moment?
