### ISSUE TITLE
/scripts/test_inference_quantized.sh: eval: line 39: syntax error near unexpected token `('

### ISSUE THREAD

**Issue by gogoods** [THUDM/CodeGeeX#147]
<img width="463" alt="image" src="https://github.com/THUDM/CodeGeeX/assets/3422759/0b13e38c-2c94-4209-800e-58922b44b187">
<img width="1444" alt="image" src="https://github.com/THUDM/CodeGeeX/assets/3422759/9f42bd08-a200-4667-a5d8-1061bcc7555d">

模型和requirements都已安装完毕，推理脚本运行失败，这是为什么呢？

**Comment by cuichenxu** [comment]
我也遇到了同样的问题，请问你解决了吗？
