### ISSUE TITLE
使用32Gv100 无法推理模型

### ISSUE THREAD

**Issue by flatblackwhite** [THUDM/CodeGeeX#158]
![image](https://github.com/THUDM/CodeGeeX/assets/22386567/c9c852ca-188e-4f97-8f9c-0719bf65ae8a)

**Comment by Aglaia11** [comment]
一样的，显存爆了

**Comment by Stanislas0** [comment]
这是内存不够的问题，导致进程被杀。V100是可以跑CodeGeeX模型的

**Comment by Aglaia11** [comment]
好的，谢谢，可以运行了。


| |
XINXIN
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年6月6日 21:54 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [THUDM/CodeGeeX] 使用32Gv100 无法推理模型 (Issue #158) |

这是内存不够的问题，导致进程被杀。V100是可以跑CodeGeeX模型的

**Comment by xwsjunjie** [comment]
这至少要多大的内存
