### ISSUE TITLE
How to disable CodeGeeX plugin in specific files, such as markdown？

### ISSUE THREAD

**Issue by rockbenben** [THUDM/CodeGeeX#16]
I usually write articles in VS Code, and the format of the articles is markdown.

However, when CodeGeeX is enabled, it makes markdown editing very slow, so I have to disable it.

Is there a way to only disable CodeGeeX in markdown files?

**Comment by Stanislas0** [comment]
> I usually write articles in VS Code, and the format of the articles is markdown.
> 
> However, when CodeGeeX is enabled, it makes markdown editing very slow, so I have to disable it.
> 
> Is there a way to only disable CodeGeeX in markdown files?

Hi, thanks so much for your feedback! Currently, one can only disable CodeGeeX globally by clicking the logo in the bottom line. We will add this function that allows one to disable a specific logo in the next version.

**Comment by Stanislas0** [comment]
> I usually write articles in VS Code, and the format of the articles is markdown.
> 
> However, when CodeGeeX is enabled, it makes markdown editing very slow, so I have to disable it.
> 
> Is there a way to only disable CodeGeeX in markdown files?

@rockbenben Hi! We have updated v1.0.7, and this feature has been added. You can now disable a specific language by clicking the logo on the bottom. Please have a try!

**Comment by rockbenben** [comment]
> > I usually write articles in VS Code, and the format of the articles is markdown.
> > However, when CodeGeeX is enabled, it makes markdown editing very slow, so I have to disable it.
> > Is there a way to only disable CodeGeeX in markdown files?
> 
> @rockbenben Hi! We have updated v1.0.7, and this feature has been added. You can now disable a specific language by clicking the logo on the bottom. Please have a try!

Great job, and the new version runs faster!
