### ISSUE TITLE
Does CodeGeeX send my code to external server?

### ISSUE THREAD

**Issue by AndreaPi** [THUDM/CodeGeeX#19]
Once I install the CodeGeeX VSCode extension, does it send any data to external servers? In particular, does it send my source code to external servers? I suggest that you add a detailed privacy policy, like Intellicode did, stating precisely if source code is ever sent to external servers, and if it is, whose servers are those (Tsinghua University, I guess?).

https://learn.microsoft.com/en-us/visualstudio/intellicode/intellicode-privacy

**Comment by Stanislas0** [comment]
> Once I install the CodeGeeX VSCode extension, does it send any data to external servers? In particular, does it send my source code to external servers? I suggest that you add a detailed privacy policy, like Intellicode did, stating precisely if source code is ever sent to external servers, and if it is, whose servers are those (Tsinghua University, I guess?).
> 
> https://learn.microsoft.com/en-us/visualstudio/intellicode/intellicode-privacy

Hi! Thanks for your feedback! We actually have declared the privacy policy on the homepage of the extension. We will also add it to the incoming documentation. To answer your question, the CodeGeeX extension does send data to external servers, because it needs GPUs to do the inference of a large code generation model (which is difficult to run locally, we are trying to compress it but it'll still need a considerable amount of computation). 

When you install the extension for the first time, we'll ask if you accept to support our further research by allowing us to store the query of your code. Otherwise, none of your code will be stored. This is disabled by default and one can change it at any time in the extension settings.

**Comment by AndreaPi** [comment]
Hi @Stanislas0 first of all, thanks for your reply! I know that there's a privacy policy on the extension page

https://marketplace.visualstudio.com/items?itemName=aminer.codegeex

but in my personal opinion it's not detailed enough. For example, it doesn't explain that, even if you refuse to share the code for research purposes, it will still send code to your servers (I guess Tshinghua University servers?) to perform inference. Of course, anyone working on LLMs understand that the average VS Code user doesn't have the compute to perform inference on-prem with a 13B LLM. However, I still think it's better to write it down explicitly, since 

1. I hope you'll get a lot of usage also from people outside the LLM community (I'm spamming your extension among my friends 😁)
2. users working in a business environment need this kind of stuff to be spelled out explicitly, so that they can go through the appropriate processes in order to know if they're allowed to use the extension or not.

Your current policy is

> We highly respect the privacy of your code. The code is only used as the input of CodeGeeX to assist your programming. At the first time of usage, we will ask if you agree to share the generated code only for research purpose (disabled by default).

 I suggest that you extend it to something like (**disclaimer: I'm not a lawyer and this is not valid legalese**).

> ### Privacy
>  We highly respect the privacy of your code. Your code is only used as the input of CodeGeeX to assist your programming. Your code is sent to our servers to perform inference, because, given the sheer size of the model, it's presently not feasible to run it locally. When you install the extension for the first time, we ask if you accept to support our further research by allowing us to store the query of your code. Otherwise, none of your code is stored. This is disabled by default and one can change it at any time in the extension settings.
> ### Data residency
> When you generate code with CodeGeeX, the input code you submit may leave your geography. It will be processed by IntelliCode services located in XXXXX.

Best of luck with your project, and keep up the good work!

**Comment by Stanislas0** [comment]
Hi @AndreaPi, thank you so much for this valuable advice! I think your concern is very reasonable and we'll update a more detailed privacy policy. I'll let you know once it's updated :)
