### ISSUE TITLE
微信开发者交流群进不了了

### ISSUE THREAD

**Issue by huawuque404** [THUDM/CodeGeeX#20]
加了"小呆"之后，没有自动邀请入群，叫他拉我进群，他回复“小呆暂时不支持私聊了”。
![image](https://user-images.githubusercontent.com/109327586/202500422-96931100-d4aa-4ef3-a123-a8fbc168dca5.png)

**Comment by Stanislas0** [comment]
> 加了"小呆"之后，没有自动邀请入群，叫他拉我进群，他回复“小呆暂时不支持私聊了”。 ![image](https://user-images.githubusercontent.com/109327586/202500422-96931100-d4aa-4ef3-a123-a8fbc168dca5.png)

您好！不好意思小呆遇到一些故障，暂时无法自动拉群。请您扫这个二维码入群：https://lfs.aminer.cn/misc/wangshan/pretrain/codegeex/static/wechat.jpg

**Comment by huawuque404** [comment]
> > 加了"小呆"之后，没有自动邀请入群，叫他拉我进群，他回复“小呆暂时不支持私聊了”。 ![image](https://user-images.githubusercontent.com/109327586/202500422-96931100-d4aa-4ef3-a123-a8fbc168dca5.png)
> 
> 您好！不好意思小呆遇到一些故障，暂时无法自动拉群。请您扫这个二维码入群：https://lfs.aminer.cn/misc/wangshan/pretrain/codegeex/static/wechat.jpg

好的，谢谢
