### ISSUE TITLE
提一个优化意见

### ISSUE THREAD

**Issue by menshen** [THUDM/CodeGeeX#210]
我使用Android Studio开发flutter平台应用，使用dart语言
现在一个问题非常困扰我
`ChannelManager.upload2tos(logPath, "out.zip", "****/log/$formattedDate/$zipFileName");") ;`
上面这段是用codegeex生成的代码，注意后面的");");，每次接纳codegeex生成后的代码我都需要手动删除最后几个字符，并且很容易删错，是否在生成代码的时候再考虑下商米阿文，如果后面已经有了");，就不要再生成");了。
希望采纳。

**Comment by crazygo** [comment]
@menshen 感谢你的反馈，我们会优化这个问题。
