### ISSUE TITLE
vscode里CodeGeeX不能提示代码了？

### ISSUE THREAD

**Issue by zhangyuanliang** [THUDM/CodeGeeX#228]
之前vscode里敲代码CodeGeeX会给大量代码提示，今天发现不提示了，重装了下CodeGeeX也不行

**Comment by Emperal** [comment]
我之前也有这个问题，把电脑用户名改成英文的试一试

**Comment by yangnian12** [comment]
我这里也不行了，版本是2.22.14，怎么解决呢

![Image](https://github.com/user-attachments/assets/870287dd-1eb6-42df-835e-e2e960957801)
