### ISSUE TITLE
能不能换个按键？

### ISSUE THREAD

**Issue by Nipers** [THUDM/CodeGeeX#23]
tab键对于代码书写过于重要了，有时候我想把代码对齐，会不小心输入我不想要的代码，能不能把Tab键谎称一个不常用的键呢？比如让用户自定义按键。

**Comment by Stanislas0** [comment]
> tab键对于代码书写过于重要了，有时候我想把代码对齐，会不小心输入我不想要的代码，能不能把Tab键谎称一个不常用的键呢？比如让用户自定义按键。

感谢您的反馈！我们研究下VS Code是否支持快捷键热更新，如果支持之后的版本会加入到设置中。

**Comment by Nipers** [comment]
非常感谢学长的回复，CodeGeeX很好用，我宣传给实验室的同学们

Qinkai ***@***.***> 于2022年11月29日周二 19:34写道：

**Comment by Stanislas0** [comment]
> 

@Nipers 感谢支持！其实VS Code本身支持修改各种插件快捷键的功能，按command+k接command+s，可以调出所有快捷键列表，找到editor.action.inlineSuggest.commit即可修改成任意键，如下图所示：

![CleanShot 2022-11-30 at 12 55 23@2x](https://user-images.githubusercontent.com/26864197/204711281-e9f8d912-0160-4286-a10a-a4f8a23de2b6.png)

**Comment by Nipers** [comment]
多谢学长的优秀工作为我带来的便利

Qinkai ***@***.***> 于2022年11月30日周三 12:59写道：
