### ISSUE TITLE
开发PyCharm插件

### ISSUE THREAD

**Issue by koking0** [THUDM/CodeGeeX#25]
看效果感觉很不错，后面有开发PyCharm插件的计划吗。

**Comment by Stanislas0** [comment]
> 看效果感觉很不错，后面有开发PyCharm插件的计划吗。

您好！CodeGeeX for Jetbrains系列插件已经在内测了，欢迎扫码加入开发者群体验！

![6181669883547_ pic](https://user-images.githubusercontent.com/26864197/205004563-59776cf0-10fe-4344-8dea-c26fa932a73d.jpg)

**Comment by Stanislas0** [comment]
> 看效果感觉很不错，后面有开发PyCharm插件的计划吗。

@koking0 您好！我们的Jetbrains版插件已经上线，[点击下载](https://plugins.jetbrains.com/plugin/20587-codegeex)或在IDE内搜索“codegeeex”安装，欢迎体验和反馈建议！
