### ISSUE TITLE
vscode插件的跨文件和项目级问答无法生成回答

### ISSUE THREAD

**Issue by jiang-yuan** [THUDM/CodeGeeX#253]
![PixPin_2024-07-09_21-27-59](https://github.com/THUDM/CodeGeeX/assets/36291537/e3ea0590-26d3-4512-8039-9a8e669dd1f1)
一直failed to fetch

**Comment by crazygo** [comment]
你好，我测试了下是可以关联文件的，请检查一下 vscode 是否有配置代理，或者机器是否能够连接到网络。
如仍有问题，欢迎添加我的微信 `nob301` 排查问题，谢谢。
![CleanShot 2024-07-09 at 23 24 43@2x](https://github.com/THUDM/CodeGeeX/assets/9395888/f4234935-e546-4e27-83f6-edadc621d9e4)

**Comment by jiang-yuan** [comment]
目前openfiles不能使用如图错误,currentfiles和recentfiles可以正常回答。
另外请问openfiles和recentfiles具体区别是什么呢？

**Comment by jiang-yuan** [comment]
可能是被限制100kb以上的文件上传,这个插件后台有上传文件

**Comment by crazygo** [comment]
> 可能是被限制100kb以上的文件上传,这个插件后台有上传文件

使用 at 功能的时候，会在请求时带着被提及的文件。这会导致请求体偏大，如果网络环境有限制，会导致发送失败。

我们记下了这个问题，想办法去优化。谢谢反馈。
