### ISSUE TITLE
两天收到四个营销短信，还要脸不

### ISSUE THREAD

**Issue by catusax** [THUDM/CodeGeeX#263]
中午30s连续收到两条，已举报 🖕🏻

![332c41a690e3bdd1f554b1bd83878176](https://github.com/user-attachments/assets/9ab29052-0478-4785-b4a5-78c8699d78d0)

![77b9cb85522e9eff18a3172df18b2363](https://github.com/user-attachments/assets/de647840-9dbd-4fd2-bcd9-b2c4a0f70986)

**Comment by Candlest** [comment]
👀
