### ISSUE TITLE
Mainframe programming languages ?

### ISSUE THREAD

**Issue by Ehplodor** [THUDM/CodeGeeX#3]
Hi, fantastic work. 

Would it be possible to integrate COBOL and other mainframe related programming languages like JCL for example ? This would be super useful and the codebase is huge !

For the purpose of original developments as well as for the translation part.

**Comment by Stanislas0** [comment]
Hi! Thanks for your attention to CodeGeeX. 

I think it would be no problem for CodeGeeX to master mainframe languages when the code data is available. In the current pre-training paradigm, it can be easily extended to other languages. But I guess these languages are more commonly used in business. I wonder if the codebase is publicly accessible.

CodeGeeX is an open-source project mainly for research purposes. Currently, we don't have a plan to support mainframe programming languages. It might be possible in the future if this addresses some interesting research problems.
