### ISSUE TITLE
Add Extension to OpenVSX

### ISSUE THREAD

**Issue by Aravindan22** [THUDM/CodeGeeX#38]
I'm a fan of Gitpod, for having this extension in the gitpod vscode editor, it should be available in OpenVSX
Can you guys please add this extension to OpenVSX?

**Comment by tennox** [comment]
It's often just a matter of running `npx ovsx publish` - you can also check the [full guide for publishing](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)

**Comment by Stanislas0** [comment]
> @maintainers: It's often just a matter of running `npx ovsx publish` - you can also check the [full guide for publishing](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)

Hi! It's already in https://open-vsx.org/extension/AMiner/codegeex.
