### ISSUE TITLE
Missing menu entries at Jetbrains IDE?

### ISSUE THREAD

**Issue by DigiLive** [THUDM/CodeGeeX#39]
Should there CodeGeeX entries in serveral menus/windows at the JetBrains IDE's?
E.g. PHPStorm > Main Menu > Tools.

I can't find any way to switch between the 3 advertised modes.

**Comment by Stanislas0** [comment]
> Should there CodeGeeX entries in serveral menus/windows at the JetBrains IDE's? E.g. PHPStorm > Main Menu > Tools.
> 
> I can't find any way to switch between the 3 advertised modes.

Hi! To switch between modes in JetBrains IDE, you just need to use shortcuts. Stealth mode is by default, if you want to use interactive mode, press ``ctrl+\`` to trigger it. For other functions like 'Generate Comment', just select a part of the code, then right-click to find CodeGeeX options.
