### ISSUE TITLE
Unable to install the CodeGeeX extension of VS Studio

### ISSUE THREAD

**Issue by AlexIca82** [THUDM/CodeGeeX#44]
Dear all,

I've just clicked on the "install button" and the installation has not startted.

Could you help?

Thanks in advance.

**Comment by Stanislas0** [comment]
Hi! Do you use VS Code or Visual Studio? CodeGeeX doesn't support Visual Studio for now. Please use VS Code instead.

**Comment by AlexIca82** [comment]
Hi Stanislas0, I got VS Code now and it works.

Thank you.
