### ISSUE TITLE
Any option to limit CodeGeeX generation area?

### ISSUE THREAD

**Issue by D0ctorWh0** [THUDM/CodeGeeX#46]
For example I have a method and want CodeGeeX to fill it with code, but it generating a lot of other methods I don't need. Is there any option to limit CodeGeeX generation area to (for example) current method?
![image](https://user-images.githubusercontent.com/13037461/210603710-81c50e00-7164-4c94-9649-16a7a7de6a41.png)

**Comment by Stanislas0** [comment]
Hi! Thanks for your feedback. We'll fix this error in the next version.

**Comment by codelast** [comment]
这个也是我使用的时候发现很恼人的一个问题，我在method的大括号之间回车，它补全的应该是大括号里的内容，也就是当前method，但实际上会乱补一通

**Comment by Stanislas0** [comment]
This problem has been fixed in the most recent version.
