### ISSUE TITLE
copy a lot（直接复制后面的代码）

### ISSUE THREAD

**Issue by shenjackyuanjie** [THUDM/CodeGeeX#47]
![image](https://user-images.githubusercontent.com/54507071/211278021-729f68cf-0423-4658-af6f-510a93baf17e.png)
如图，他会直接复制后面已经写好的代码

**Comment by Stanislas0** [comment]
你好，感谢您的反馈，这个bug应该是由于缓存机制导致的，我们改进一下

**Comment by shenjackyuanjie** [comment]
好的~
谢谢！

**Comment by codelast** [comment]
确实，我也发现这个现象很多次了，让人抓狂的bug

**Comment by Stanislas0** [comment]
您好！在新版本中我们已经修复了该bug，请再试一下，如有问题欢迎反馈，谢谢！

**Comment by shenjackyuanjie** [comment]
好的~ 回去试一试
