### ISSUE TITLE
你好 请问 CodeGeeX 支持哪些编程语言?

### ISSUE THREAD

**Issue by wujunze** [THUDM/CodeGeeX#48]
你好 请问 CodeGeeX 支持哪些编程语言, 支持 Solidity 吗?

**Comment by Stanislas0** [comment]
你好，目前支持的是这些语言：https://github.com/THUDM/CodeGeeX/blob/main/codegeex/data/data_utils.py#L7，根据训练量，各种语言的表现会有差异。目前还不支持 Solidity

**Comment by wujunze** [comment]
Thanks @Stanislas0

**Comment by wujunze** [comment]
请问后续有计划支持 Solidity 吗

**Comment by Stanislas0** [comment]
> 

暂时还没有这个计划，不过如果有相关数据的话，可以尝试一下。

**Comment by wujunze** [comment]
如果需要 Solidity  代码数据相关帮助,  我可以帮忙
