### ISSUE TITLE
PyTorch Int8 inference time cost

### ISSUE THREAD

**Issue by mu-zizi** [THUDM/CodeGeeX#52]
Hi，我用Int8 精度在A100机器（CUDA 11.0）上进行推理，能看到CodeGeeX只占15GB 显存，而且GPU 利用率也是满的，我每次都输入一条1024序列（不复用Cache），它的速度大概是单Token 280ms，这个是正常的么。我是不是有地方没有调对？因为 [codegeex-fastertransformer](https://github.com/CodeGeeX/codegeex-fastertransformer) 项目中的对比表，这种方式应该是75ms左右。

**Comment by Stanislas0** [comment]
> Hi，我用Int8 精度在A100机器（CUDA 11.0）上进行推理，能看到CodeGeeX只占15GB 显存，而且GPU 利用率也是满的，我每次都输入一条1024序列（不复用Cache），它的速度大概是单Token 280ms，这个是正常的么。我是不是有地方没有调对？因为 [codegeex-fastertransformer](https://github.com/CodeGeeX/codegeex-fastertransformer) 项目中的对比表，这种方式应该是75ms左右。

Hi, 这个速度不太正常。输入是1024，输出是多长呢？默认是会使用增量推理，输入的时候只要给prompt部分就行了，不需要做padding。

**Comment by mu-zizi** [comment]
> Hi, 这个速度不太正常。输入是1024，输出是多长呢？默认是会使用增量推理，输入的时候只要给prompt部分就行了，不需要做padding。

我是直接调用的 [CodeGeeXModel.forward()](https://github.com/THUDM/CodeGeeX/blob/main/codegeex/paddle/codegeex_model.py#L947) 函数，输入1024的id序列，输出单个id，平均下来的预测时间。应该是没做Padding的，例如单步预测大概像这样：
```python
            logits = model(
                tokens_ids, # shape: [1, 1024]
                position_ids,  # shape: [1, 1024]
                attention_mask,  # shape: [1024, 1024]
                )
            logits = logits[:, -1].view(1, -1).contiguous()
            probs = torch.softmax(logits, dim=-1).cpu().numpy()
```

**Comment by mu-zizi** [comment]
嗯嗯，感谢，我试试FasterTransformer版的
