### ISSUE TITLE
If no GPU, can CodeGeex work well on CPU RAMs?

### ISSUE THREAD

**Issue by cxsjabc** [THUDM/CodeGeeX#56]
Currently, my computer has no GPU card, can we do the research, just slower?
Another question, can we reduce the model(~26GB) to smaller file, is it easier to test?

**Comment by Stanislas0** [comment]
> Currently, my computer has no GPU card, can we do the research, just slower? Another question, can we reduce the model(~26GB) to smaller file, is it easier to test?

Hi! CodeGeeX works fine without GPU, it just get much slower and you need large CPU memory (>32GB). We can reduce the model to a smaller file using quantization (~15GB) and it's currently supported. Please check out https://github.com/THUDM/CodeGeeX/blob/main/codegeex/quantization/quantize.py
For inference on CPU, you just need to modify this file: https://github.com/THUDM/CodeGeeX/blob/main/tests/test_inference.py#L139

**Comment by ccteam** [comment]
ok, thanks very much.

**Comment by cxsjabc** [comment]
Thanks, i will try.

**Comment by davideuler** [comment]
Is there any guys run it successfully on CPU ?

**Comment by CharellKing** [comment]
when Building CodeGeeX model ..., The process is killed. I hava total 64 GB ram；I run it on CPU:
`python /home/andy/code/CodeGeeX/tests/test_inference.py         
	--prompt-file /home/andy/code/CodeGeeX/tests/test_prompt.txt         
	--tokenizer-path /home/andy/code/CodeGeeX/codegeex/tokenizer/         
	--micro-batch-size 1         
	--out-seq-length 1024         
	--temperature 0.8         
	--top-p 0.95         
	--quantize         
	--top-k 0         
	--greedy         
	--num-layers 39             
	--hidden-size 5120             
	--num-attention-heads 40             
	--max-position-embeddings 2048             
	--attention-softmax-in-fp32             
	--load /home/andy/code/CodeGeeX/codegeex_13b.pt             
	--layernorm-epsilon 1e-5             
	--fp16             
	--ws-encoding-start-id 10             
	--ws-encoding-length 10             
	--make-vocab-size-divisible-by 52224             
	--seq-length 2048`

**Comment by CharellKing** [comment]
> when Building CodeGeeX model ..., The process is killed. I hava total 64 GB ram；I run it on CPU: python /home/andy/code/CodeGeeX/tests/test_inference.py --prompt-file /home/andy/code/CodeGeeX/tests/test_prompt.txt --tokenizer-path /home/andy/code/CodeGeeX/codegeex/tokenizer/ --micro-batch-size 1 --out-seq-length 1024 --temperature 0.8 --top-p 0.95 --quantize --top-k 0 --greedy --num-layers 39 --hidden-size 5120 --num-attention-heads 40 --max-position-embeddings 2048 --attention-softmax-in-fp32 --load /home/andy/code/CodeGeeX/codegeex_13b.pt --layernorm-epsilon 1e-5 --fp16 --ws-encoding-start-id 10 --ws-encoding-length 10 --make-vocab-size-divisible-by 52224 --seq-length 2048

I found the percent of ram is 99%；when i run this script.
