### ISSUE TITLE
本地部署的推荐配置

### ISSUE THREAD

**Issue by yonghanzhuce** [THUDM/CodeGeeX#57]
我使用Nvdia RTX 5000（16GB显存）显卡来本地运行codegeex，程序运行起来了，但是速度很慢。
通过注释生成一个20行左右的函数，会花费1分钟~2分钟。
请问本地部署有推荐的配置吗，期望通过注释生成一般函数控制在10秒左右完成，谢谢。

**Comment by Stanislas0** [comment]
您好！可以试一下codegeex的fastertransformer版本（INT8+FT），速度会快很多：https://github.com/CodeGeeX/codegeex-fastertransformer
