### ISSUE TITLE
model download link not working

### ISSUE THREAD

**Issue by epinnock** [THUDM/CodeGeeX#63]
Hi the link to request the model is not working: https://models.aminer.cn/codegeex/download/request
I've gotten the email but the links in the email are not working when using aria2

  -> [AbstractCommand.cc:789] errorCode=19 CUID#12 - Name resolution for codegeex.11cbd89742fe4310756045060652d091.r2.cloudflarestorage.com failed:Timeout while contacting DNS servers

**Comment by Stanislas0** [comment]
> Hi the link to request the model is not working: https://models.aminer.cn/codegeex/download/request I've gotten the email but the links in the email are not working when using aria2
> 
> -> [AbstractCommand.cc:789] errorCode=19 CUID#12 - Name resolution for codegeex.11cbd89742fe4310756045060652d091.r2.cloudflarestorage.com failed:Timeout while contacting DNS servers

Hi! I just tested the download link and it works fine. Please check if the firewall blocks the Cloudflare service, and try again to get another link.

**Comment by epinnock** [comment]
Thanks
