### ISSUE TITLE
How can I generate my model for test?

### ISSUE THREAD

**Issue by ccteam** [THUDM/CodeGeeX#64]
Hi pals,
   Found that the model files you provided are too big. We can't test locally.
   So how can i generate my local model for my test?

  Thanks.

**Comment by Stanislas0** [comment]
> Hi pals, Found that the model files you provided are too big. We can't test locally. So how can i generate my local model for my test?
> 
> Thanks.

Hi! What's your local hardware configuration? A GPU card with at least 24GB is needed for testing.

**Comment by ccteam** [comment]
Hi, currently, my GPU card is weak, 2GB.
Is there any method to decrease the model? 
As my working language, c and c++ are more often.
Could the model only train c languages?  Then the model should be smaller.
Then I think i can test myself.

Another question, the model dataset is also open source?

**Comment by Stanislas0** [comment]
> Hi, currently, my GPU card is weak, 2GB. Is there any method to decrease the model? As my working language, c and c++ are more often. Could the model only train c languages? Then the model should be smaller. Then I think i can test myself.
> 
> Another question, the model dataset is also open source?

I understand your concern, but fewer parameters will result in a poorer model, 2GB RAM is far from enough for CodeGeeX. In this case, you can directly use our [VS Code](https://marketplace.visualstudio.com/items?itemName=aminer.codegeex) or [Jetbrains](https://plugins.jetbrains.com/plugin/20587-codegeex) extensions, or [API](https://tianqi.aminer.cn/open/en-US).

**Comment by ccteam** [comment]
Ok, got it, thanks very much!
