### ISSUE TITLE
VSCODE 一直弹出CodeGeeX Guide页面

### ISSUE THREAD

**Issue by ixjx** [THUDM/CodeGeeX#66]
VSCODE 一直弹出CodeGeeX Guide页面

VSCODE版本：
版本: 1.75.1 (user setup)
提交: 441438abd1ac652551dbe4d408dfcec8a499b8bf
日期: 2023-02-08T21:32:34.589Z
Electron: 19.1.9
Chromium: 102.0.5005.194
Node.js: 16.14.2
V8: 10.2.154.23-electron.0
OS: Windows_NT x64 6.3.9600
沙盒化: No

CodeGeeX 版本：v1.1.2

**Comment by Stanislas0** [comment]
您好！可以升级到最新的1.1.3版本，试一试该问题是否还会出现？

**Comment by ixjx** [comment]
已修复
