### ISSUE TITLE
test_inference_oneflow 报错问题

### ISSUE THREAD

**Issue by genius0182** [THUDM/CodeGeeX#68]
![image](https://user-images.githubusercontent.com/24863486/218957371-6f4fa2ce-c0f7-4783-8a7e-01869da401f7.png)
![image](https://user-images.githubusercontent.com/24863486/218957407-7ac7603b-f675-4852-9249-76dd2efa9663.png)

**Comment by Stanislas0** [comment]
Hi! Please refer to this doc: https://github.com/Oneflow-Inc/one-codegeex/wiki/How-to-run-CodeGeeX-in-OneFlow. You might need a nightly version of oneflow.

**Comment by q497629642** [comment]
试过了还是不行
