### ISSUE TITLE
Slack Link in GitHub and VSCode Marketplace are Dead

### ISSUE THREAD

**Issue by BenjaminHCCarr** [THUDM/CodeGeeX#73]
The current link: https://join.slack.com/t/codegeexworkspace/shared_invite/zt-1m76zecsi-~JW59Jmvx09lX4Pqv9oE_w

is Dead in https://github.com/THUDM/CodeGeeX/blob/main/README.md?plain=1#L7

and at https://marketplace.visualstudio.com/items?itemName=aminer.codegeex

**Comment by Stanislas0** [comment]
Thanks for the information. I've updated the [link](https://join.slack.com/t/codegeexworkspace/shared_invite/zt-1q73pz8dc-23zIhl1ORw1rKIXXmkxdvA).
