### ISSUE TITLE
关于wsl2使用的一些问题

### ISSUE THREAD

**Issue by yi-ge-dian** [THUDM/CodeGeeX#82]
如何在wsl2使用这个插件，当我第一次使用的时候报了这个错误。

![image](https://user-images.githubusercontent.com/68337798/224496265-8b905241-5f52-4bc8-afa8-2216657b8c28.png)

于是我根据这个链接 https://www.cnblogs.com/lemontreeyi/p/16950898.html#/c/subject/p/16950898.html 完成了将wsl指向本机的代理并打开了防火墙及其对应的端口。

但当我再次使用的时候，他仍然报这个错误，我现在已经正常的通过 `curl www.google.com` 获取到文本内容了，接下来应该如何处理，期待您的回复。

**Comment by Stanislas0** [comment]
您好，看起来是在VS Code中使用了proxy代理，请问这样配置之后，其他需要联网的插件使用正常吗？

**Comment by yi-ge-dian** [comment]
您好，请问其他联网的插件是否有一些推荐，我的wsl 目前拥有的插件如下：
![image](https://user-images.githubusercontent.com/68337798/224652384-b11379fc-6e91-488d-9eb5-4fb313f87eac.png)

**Comment by yi-ge-dian** [comment]
> @yi-ge-dian 请问如何解决的呢？我也按照你提供的链接的方法配置了防火墙，现象跟你提到的一致。

没再折腾了，直接换成了GitHub Copilot ，如果你不是学生的话，可以尝试一下阿里的通义灵码。
