### ISSUE TITLE
can set the prompt in only one language?

### ISSUE THREAD

**Issue by shenjilina** [THUDM/CodeGeeX#9]
I don't want to see Python prompts in the js file

**Comment by Stanislas0** [comment]
Hi! Which mode do you use? If you're using stealth or interactive mode, language is determined by the suffix of your current file. If you're using the prompt mode, the default templates are written in Python. It's easy to add your own templates for JS by specifying the path:
![CleanShot 2022-10-17 at 13 43 12@2x](https://user-images.githubusercontent.com/26864197/196098444-70f1412e-78cc-4488-bad0-dd29e5900b85.png)
